data<-read.csv("household_power_consumption.txt",sep=";",dec=".",colClasses=c(rep("character",9)))
data$Date <- as.Date(data$Date , "%d/%m/%Y")
workdata <- subset(data, Date >=  "2007-02-01" & Date <=  "2007-02-02")
workdata$Global_active_power <- as.numeric(workdata$Global_active_power)
workdata$DayOfTheWeek <- weekdays(workdata$Date, abbr = T)
png(filename = "plot3.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white",  res = NA)
par(mar=c(3,4,2,2))
plot(workdata$Sub_metering_1,type="l", pch="", ylab="Energy sub metering",xaxt='n')
lines(workdata$Sub_metering_2, col="red")
lines(workdata$Sub_metering_3, col="blue")
axis(1, c(1,1441,2880), c("Thu","Fri","Sat"))
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd="1")
dev.off()