data<-read.csv("household_power_consumption.txt",sep=";",dec=".",colClasses=c(rep("character",9))
data$Date <- as.Date(data$Date , "%d/%m/%Y")
workdata <- subset(data, Date >=  "2007-02-01" & Date <=  "2007-02-02")
workdata$Global_active_power <- as.numeric(workdata$Global_active_power)
png(filename = "plot1.png", width = 480, height = 480, units = "px", pointsize = 12, bg = "white",  res = NA)
hist(workdata$Global_active_power,col="red",main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
